export const projects = [
  {
    title: "Chrip.",
    tags: ["Next.js", "TailwindCSS"],
    visit: "https://chrip.vercel.app/",
    id: 0,
    desc: "Creating landing page from design",
    source: "https://github.com/FajriSiiv/chrip",
  },
  {
    title: "Github Search Profil",
    tags: ["NEXT.js", "API", "TailwindCSS"],
    visit: "https://github-search-fajri.vercel.app/",
    id: 1,
    desc: "Searching github profile and consume API from github.",
    source: "https://github.com/FajriSiiv/github-search",
  },
  {
    title: "Spotify Clone",
    tags: ["React", "Context", "Styled Components", "API"],
    visit: "https://spotify-clone-gilt.vercel.app/",
    id: 2,
    desc: "Cloning Spotify App with react,usecontext, API Consume",
    source: "https://github.com/FajriSiiv/spotify-clone/tree/master",
  },
  {
    title: "Dashboard",
    tags: ["Next.js", "Javascript", "TailwindCSS"],
    visit: "https://dashboard-2-omega.vercel.app/",
    id: 3,
    desc: "Simple dashboard your sosial media trafic",
    source: "https://github.com/FajriSiiv/dashboard-2",
  },
  {
    title: "React Cart",
    tags: ["React", "Javascript", "Styled Components"],
    visit: "https://siiv-cart.netlify.app/",
    id: 4,
    desc: "Creating e-commerce website with React.js and style components.",
    source: "https://github.com/FajriSiiv/shop_cart",
  },
  {
    title: "Product Page",
    tags: ["React", "Javascript", "Styled Components"],
    visit: "https://product-page-ifi8bhi1n-fajrisiiv.vercel.app/",
    id: 5,
    desc: "Creating details product page with cool design",
    source: "https://github.com/FajriSiiv/product-page",
  },
  {
    title: "Easybank",
    tags: ["React", "Javascript", "CSS"],
    visit: "https://easybank-woad.vercel.app/",
    id: 6,
    desc: "Creating cool landing page with React.js and CSS",
    source: "https://github.com/FajriSiiv/easybank",
  },
  {
    title: "E-Commerce",
    tags: ["Next.js", "Javascript", "TailwindCSS", "Redux"],
    visit: "https://shopcart-redux.vercel.app/",
    id: 7,
    desc: "e-commerce consume API and adding items into cart.",
    source: "https://github.com/FajriSiiv/shopcart1",
  },
  {
    title: "Movie APP",
    tags: ["React.js", "Styled-Components", "API"],
    visit: "https://movie-app-pi-rose.vercel.app/",
    id: 7,
    desc: "Movie APP consume data with API and send rate movie with API rule",
    source: "https://github.com/FajriSiiv/movie-app",
  },
  
];

export const TimeLineData = [
  { year: 2019, text: "Started learning website" },
  { year: 2020, text: "Code and Build example projects" },
  { year: 2021, text: "Worked as a Frontend Developer" },
  { year: 2022, text: "Worked as a Freelancer" },
];
